# lab8
question 1

第五行的 throw; 已經把東西丟出去，就不會再執行第六行的cout了

question 2

會跑出 : I love C++

因為此例 try 跑完會跑進 catch ，而當 catch 跑完後會接著把 catch block 外的程式跑完
